---
- hosts: marisma002
  gather_facts: no
  vars:
    proxmox_api_user: "root"
    proxmox_api_password: "*********"
    proxmox_api_host: "localhost"
    proxmox_api_port: "8006"
  tasks:
    - name: Get next vmid
      shell: pvesh get /cluster/nextid --username "{{ proxmox_api_user }}" --password "{{ proxmox_api_password }}" --host "{{ proxmox_api_host }}" --port "{{ proxmox_api_port }}"
      register: next_vmid_raw

    - set_fact:
        next_vmid: "{{ next_vmid_raw.stdout | int }}"

    - name: Write next vmid to file
      copy:
        content: "{{ next_vmid }}"
        dest: next_vmid.txt
