- name: Create a Proxmox VM
  hosts: marisma002  
  gather_facts: false
  vars:
    proxmox_api_user: 'administrador'
    proxmox_api_password: '12345'
    proxmox_api_host: 'localhost'
    proxmox_api_port: '8006'
    proxmox_vm_name: 'prueba1'
    proxmox_vm_node: 'marisma002'
    proxmox_vm_cores: 2
    proxmox_vm_memory: 4096
    proxmox_vm_iso: '/mnt/pve/NAS/iso/ubuntu-22.04.1-desktop-amd64.iso'
    proxmox_vm_disk_size: 20G
    proxmox_vm_storage_pool: '2ASIR'
    proxmox_kvm:
      api_user: "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_password }}"
      api_host: "{{ proxmox_api_host }}"
      api_port: "{{ proxmox_api_port }}"
      vmid: "{{ lookup('file', 'next_vmid.txt') | int }}"
      node: "{{ proxmox_vm_node }}"
      name: "{{ proxmox_vm_name }}"
      cores: "{{ proxmox_vm_cores }}"
      memory: "{{ proxmox_vm_memory }}"
      iso: "{{ proxmox_vm_iso }}"
      disks:
        - size: "{{ proxmox_vm_disk_size }}"
          storage: "{{ proxmox_vm_storage_pool }}"
      state: present
  tasks:
    - name: Create the Proxmox VM
      ansible_collections:
        community.general:
          ansible_kvm:
            api_user: "{{ proxmox_kvm.api_user }}"
            api_password: "{{ proxmox_kvm.api_password }}"
            api_host: "{{ proxmox_kvm.api_host }}"
            api_port: "{{ proxmox_kvm.api_port }}"
            vmid: "{{ proxmox_kvm.vmid }}"
            node: "{{ proxmox_kvm.node }}"
            name: "{{ proxmox_kvm.name }}"
            cores: "{{ proxmox_kvm.cores }}"
            memory: "{{ proxmox_kvm.memory }}"
            iso: "{{ proxmox_kvm.iso }}"
            disks: "{{ proxmox_kvm.disks }}"
            state: "{{ proxmox_kvm.state }}"
